### ISSUE TITLE
como instalar no debian 9

### ISSUE THREAD

**Issue by contatodct** [wribeiiro/clone-whatsapp#1]
bom dia
gostaria de saber como eu posso estar instalando usando debian9 php7 apache 2.4

esta aparecendo o seguinte erro  pramim..

An Error Was Encountered

Unable to load the requested file: helpers/utils_helper.php

**Comment by wribeiiro** [comment]
Provavelmente é problema de case sensitive no nome dos arquivos, acontece isso no linux. Tente renomear os arquivos e nome da classe com lowercase

**Comment by contatodct** [comment]
como faço isso??.......pode me ajudar?
