### ISSUE TITLE
An Error Was Encountered

### ISSUE THREAD

**Issue by atorresbr** [wribeiiro/clone-whatsapp#2]
Unable to load the requested file: helpers/utils_helper.php

Hi Folks, I can't run the app through cPanel, could you help me? .. The information from the database configuration file follows. 
![Screenshot from 2021-06-07 01-02-51](https://user-images.githubusercontent.com/13744483/120957494-23520b80-c72c-11eb-893b-13b0035b3e6d.png)

**Comment by wribeiiro** [comment]
Opa, experimenta alterar o nome do arquivo tudo para lowercase  Utils_helper > utils_helper
e no arquivo application/config/autoload.php

![image](https://user-images.githubusercontent.com/20648572/121075697-e3326d80-c7ab-11eb-95cd-1aea35f07df2.png)

tambem alterar para lowercase o nome do arquivo, no linux tem esse conflito de case sensitive

**Comment by atorresbr** [comment]
> Opa, experimenta alterar o nome do arquivo tudo para lowercase Utils_helper > utils_helper
> e no arquivo application/config/autoload.php
> 
> ![image](https://user-images.githubusercontent.com/20648572/121075697-e3326d80-c7ab-11eb-95cd-1aea35f07df2.png)
> 
> tambem alterar para lowercase o nome do arquivo, no linux tem esse conflito de case sensitive

vou tentar agora :)

**Comment by wribeiiro** [comment]
Conseguiu algo?

**Comment by atorresbr** [comment]
> Conseguiu algo?

o erro continuou, mas eu comentei a linha e o erro sumi, porém surgiu esse na imagem -- Eu to tentando instalar na Hospedagem com cPanel, renomeei do diretório "clone-whatsapp" para "chat" -- (( sulamericahost.com.br/chat/ ))

segue a configuração no database.php

$active_group = 'local';
$query_builder = TRUE;

$db['local'] = array(
	'dsn'   => 'mysql:host=localhost;dbname=sulameri_chat',
	'hostname' => 'localhost',
	'username' => 'sulameri_chat',
	'password' => 'sulameri_chat',
	'database' => 'sulameri_chat',
	'dbdriver' => 'pdo',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => TRUE,
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'save_queries' => TRUE
);
![Screenshot from 2021-06-09 01-48-39](https://user-images.githubusercontent.com/13744483/121295354-4106a880-c8c5-11eb-87ce-c2d49d0d56d5.png)

**Comment by wribeiiro** [comment]
Pela mensagem é erro de configuração mesmo, se não tiver conseguido, me chama no privado posso ajudar.
